# Generated by Django 3.2.7 on 2021-10-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Feature_name', models.CharField(max_length=100)),
                ('Issue', models.CharField(max_length=250)),
                ('Time_Date', models.DateTimeField()),
            ],
        ),
    ]
